
# failure() {
#   local lineno=$1
#   local msg=$2
#   echo "Failed at $lineno: $msg"
# }
# trap 'failure ${LINENO} "$BASH_COMMAND"' ERR

source ~/term/shell.sh bash

export IGNOREEOF=1000

shopt -s histappend

set -o vi

stty -ixon

if [ -f /.production ]; then
    export PS1="{bg_red}[\u@\h \w]$ "
else
    export PS1="[\u@\h \w]$ "
fi


[ -f ~/.fzf.bash ] && source ~/.fzf.bash

if [[ -n $TMUX_WAIT_FOR ]]; then
   tmux wait-for -S $TMUX_WAIT_FOR
fi

