source ~/.xvim/helpers.vim

let g:auto_session_root = $HOME . "/.xvim_sessions"

call SourceDirectory("~/.xvim/baseline")

call plug#begin()

source ~/.xvim/plugins.vim

"" NeoBundle 'vim-airline/vim-airline'
"" NeoBundle 'vim-airline/vim-airline-themes'

Plug 'itchyny/lightline.vim'

Plug 'mkitt/tabline.vim'

let g:CommandTPreferredImplementation='lua'

Plug 'wincent/command-t', { 'do': 'cd lua/wincent/commandt/lib && make' }

call plug#end()


" don't know why but this needs to be here
source ~/.xvim/baseline/syntax.vim

call SourceDirectory("~/.xvim/functions")
call SourceDirectory("~/.xvim/plugins")
call SourceDirectory("~/.xvim/settings")

call SourceDirectory("~/.xvim/nvim")

source ~/.xvim/keymaps.vim

" allow project specific settings -- needs to be at the end
source ~/.xvim/localrc.vim


