source ~/.xvim/helpers.vim

" Python Setting {
  " set pythondll=~/.pyenv/versions/3.9.0/bin/python
  " set pythonhome=~/.pyenv/versions/3.9.0/
  " set pythonthreedll=~/.pyenv/versions/3.9.0/bin/python
  " set pythonthreehome=~/.pyenv/versions/3.9.0/
" }

" echo has('python3')
"
" set rubydll=~/.rvm/rubies/ruby-2.5.1/lib/libruby.2.5.dylib
" set rubydll=~/.rvm/rubies/ruby-2.6.3/lib/libruby.2.6.dylib
" set rubydll=~/.homebrew/Cellar/ruby@2.6/2.6.9/lib/libruby.2.6.dylib

let g:auto_session_root = $HOME . "/.xvim_sessions"

call SourceDirectory("~/.xvim/baseline")

call plug#begin()

let g:CommandTPreferredImplementation='ruby'
Plug 'wincent/command-t', { 'do': 'cd ruby/wincent/commandt/lib && make' }

source ~/.xvim/plugins.vim

Plug 'sixcircuit/powerline', { 'rtp': 'powerline/bindings/vim/' }
Plug 'mkitt/tabline.vim'

"" NeoBundle 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}
"" NeoBundle 'vim-powerline'
"" NeoBundle 'Lokaltog/vim-powerline', { 'rev' : 'develop' }

call plug#end()

" don't know why but this needs to be here
source ~/.xvim/baseline/syntax.vim

call SourceDirectory("~/.xvim/functions")
call SourceDirectory("~/.xvim/plugins")
call SourceDirectory("~/.xvim/settings")

call SourceDirectory("~/.xvim/vim")

source ~/.xvim/keymaps.vim

" allow project specific settings -- needs to be at the end
source ~/.xvim/localrc.vim


