# zmodload zsh/zprof # profile startup time

# failure() {
#   local lineno=$1
#   local msg=$2
#   echo "Failed at $lineno: $msg"
# }

# # In Zsh, $funcstack[2] can be used to get the command that caused the error
# # and $LINENO is an array where the first element holds the line number.
# trap 'failure $LINENO[1] "$funcstack[2]"' ERR

# fallback prompt
export PS1="[%n@%m %~] "

source ~/term/shell.sh zsh

# job control, if a bare name is used, fg the job
setopt auto_resume

# why would you type 'cd dir' if you could just type 'dir'?
setopt AUTO_CD

# Case insensitive globbing
setopt NO_CASE_GLOB

# Be Reasonable!
setopt NUMERIC_GLOB_SORT

# 10 second wait if you do something that will delete everything.  I wish I'd had this before...
setopt RM_STAR_WAIT

# this in combo with stty.sh allows mapping ctrl+s and ctrl+q
setopt noflowcontrol


# startup scripts "cd" so we do this here to keep the stack empty and the screen clear

# alias cd='pushd -q'
alias pd='popd -q'

function cd(){
   if [[ "$@" == "" ]]; then
      if [[ "$PWD" != $HOME ]]; then
         pushd -q ~
      else
         return 0
      fi
   else
      pushd -q "$@"
   fi
   ls
}

alias c='cd'


if [[ -n $TMUX_WAIT_FOR ]]; then
   tmux wait-for -S $TMUX_WAIT_FOR
fi

# zprof # profile startup time

